export const DEMO_BOARD = {
  id: 'board_001',
  title: 'Sleek Task',
  columnOrder: ['col_1', 'col_2', 'col_3', 'col_4', 'col_5'],
  columns: {
    col_1: { id: 'col_1', title: 'Backlog',     accentColor: '#71717A', taskIds: ['task_01','task_02','task_03','task_04','task_05'] },
    col_2: { id: 'col_2', title: 'To Do',       accentColor: '#A1A1AA', taskIds: ['task_06','task_07','task_08','task_09'] },
    col_3: { id: 'col_3', title: 'In Progress', accentColor: '#E8185A', taskIds: ['task_10','task_11','task_12','task_13'] },
    col_4: { id: 'col_4', title: 'In Review',   accentColor: '#D97706', taskIds: ['task_14','task_15','task_16'] },
    col_5: { id: 'col_5', title: 'Done',        accentColor: '#52525B', taskIds: ['task_17','task_18','task_19','task_20'] },
  },
  tasks: {
    task_01: {
      id: 'task_01', title: 'Audit accessibility across all public-facing pages',
      description: 'Run axe-core and manual screen-reader tests on landing, pricing, and docs pages. File issues for every WCAG 2.1 AA violation found.',
      priority: 'high', dueDate: '2025-03-10', assignee: 'CO',
      tags: ['a11y', 'audit'], comments: 3, attachments: 2,
      createdAt: '2025-02-01T09:00:00Z',
    },
    task_02: {
      id: 'task_02', title: 'Evaluate WebSocket vs SSE for live updates',
      description: 'Benchmark both approaches under 10k concurrent connections. Document latency, reconnect behaviour, and infra cost differences.',
      priority: 'medium', dueDate: '2025-04-20', assignee: 'AK',
      tags: ['research', 'infra'], comments: 1, attachments: 0,
      createdAt: '2025-02-03T10:00:00Z',
    },
    task_03: {
      id: 'task_03', title: 'Define data retention and GDPR deletion policy',
      description: 'Work with legal to define retention windows per data class. Implement soft-delete + scheduled hard-delete pipeline.',
      priority: 'high', dueDate: '2025-03-28', assignee: 'MJ',
      tags: ['legal', 'gdpr'], comments: 5, attachments: 1,
      createdAt: '2025-02-05T11:00:00Z',
    },
    task_04: {
      id: 'task_04', title: 'Spike: evaluate Turborepo for monorepo build caching',
      description: 'Set up a proof-of-concept with Turborepo. Measure cold and warm build times vs current setup.',
      priority: 'low', dueDate: '2025-05-01', assignee: 'ZB',
      tags: ['dx', 'build'], comments: 0, attachments: 0,
      createdAt: '2025-02-07T08:00:00Z',
    },
    task_05: {
      id: 'task_05', title: 'Design system: document spacing and grid tokens',
      description: 'Export all spacing, grid, and breakpoint tokens from Figma into a JSON token file. Wire into the CSS variable pipeline.',
      priority: 'medium', dueDate: '2025-04-10', assignee: 'ST',
      tags: ['design-system'], comments: 2, attachments: 3,
      createdAt: '2025-02-08T14:00:00Z',
    },
    task_06: {
      id: 'task_06', title: 'Implement rate limiting on all public API endpoints',
      description: 'Use a sliding-window algorithm. Limits: 100 req/min per IP, 1000 req/min per authenticated user. Return 429 with Retry-After header.',
      priority: 'high', dueDate: '2025-03-15', assignee: 'CO',
      tags: ['security', 'api'], comments: 4, attachments: 0,
      createdAt: '2025-02-10T09:00:00Z',
    },
    task_07: {
      id: 'task_07', title: 'Add OpenTelemetry tracing to the API gateway',
      description: 'Instrument all inbound requests with trace IDs. Export spans to Grafana Tempo. Ensure PII is scrubbed from span attributes.',
      priority: 'medium', dueDate: '2025-04-05', assignee: 'AK',
      tags: ['observability'], comments: 2, attachments: 1,
      createdAt: '2025-02-12T10:00:00Z',
    },
    task_08: {
      id: 'task_08', title: 'Write E2E tests for the checkout flow',
      description: 'Cover happy path, card decline, 3DS challenge, and coupon application. Use Playwright. Run in CI on every PR.',
      priority: 'high', dueDate: '2025-03-20', assignee: 'MJ',
      tags: ['testing', 'e2e'], comments: 1, attachments: 0,
      createdAt: '2025-02-14T11:00:00Z',
    },
    task_09: {
      id: 'task_09', title: 'Migrate image CDN from Cloudinary to self-hosted imgproxy',
      description: 'Set up imgproxy on Fly.io. Update all image URLs. Validate WebP/AVIF output quality. Measure p95 TTFB improvement.',
      priority: 'low', dueDate: '2025-05-15', assignee: 'ZB',
      tags: ['infra', 'perf'], comments: 0, attachments: 2,
      createdAt: '2025-02-15T08:00:00Z',
    },
    task_10: {
      id: 'task_10', title: 'Build real-time collaborative cursor presence',
      description: 'Show live cursors for all users on the same board. Use CRDT-based state sync via Yjs. Throttle cursor updates to 30fps.',
      priority: 'high', dueDate: '2025-03-05', assignee: 'CO',
      tags: ['realtime', 'collab'], comments: 7, attachments: 1,
      createdAt: '2025-02-16T09:00:00Z',
    },
    task_11: {
      id: 'task_11', title: 'Refactor auth middleware to support multi-tenancy',
      description: 'Extract tenant context from JWT claims. Scope all DB queries to tenant ID. Add integration tests for cross-tenant isolation.',
      priority: 'high', dueDate: '2025-03-12', assignee: 'AK',
      tags: ['auth', 'backend'], comments: 3, attachments: 0,
      createdAt: '2025-02-17T10:00:00Z',
    },
    task_12: {
      id: 'task_12', title: 'Redesign notification centre UI',
      description: 'Group notifications by type. Add mark-all-read, filter by category, and infinite scroll. Match new design system tokens.',
      priority: 'medium', dueDate: '2025-04-01', assignee: 'ST',
      tags: ['ui', 'design'], comments: 5, attachments: 4,
      createdAt: '2025-02-18T11:00:00Z',
    },
    task_13: {
      id: 'task_13', title: 'Optimise bundle size — target < 200 kB gzipped',
      description: 'Run webpack-bundle-analyzer. Tree-shake lodash. Replace moment.js with date-fns. Lazy-load all route-level components.',
      priority: 'medium', dueDate: '2025-04-08', assignee: 'ZB',
      tags: ['perf', 'frontend'], comments: 2, attachments: 0,
      createdAt: '2025-02-19T08:00:00Z',
    },
    task_14: {
      id: 'task_14', title: 'Code review: payment webhook handler refactor',
      description: 'Review PR #412. Check idempotency key handling, error retry logic, and Stripe signature verification. Leave inline comments.',
      priority: 'high', dueDate: '2025-03-08', assignee: 'MJ',
      tags: ['review', 'payments'], comments: 9, attachments: 0,
      createdAt: '2025-02-20T09:00:00Z',
    },
    task_15: {
      id: 'task_15', title: 'QA: mobile regression on iOS 17 Safari',
      description: 'Test all critical flows on iPhone 14 / iOS 17 Safari. Focus on date pickers, modals, and scroll behaviour. File bugs in Linear.',
      priority: 'medium', dueDate: '2025-03-18', assignee: 'ST',
      tags: ['qa', 'mobile'], comments: 4, attachments: 2,
      createdAt: '2025-02-21T10:00:00Z',
    },
    task_16: {
      id: 'task_16', title: 'Security review: OAuth2 PKCE implementation',
      description: 'Verify code_verifier entropy, state parameter handling, and redirect URI validation. Cross-reference against RFC 7636.',
      priority: 'high', dueDate: '2025-03-10', assignee: 'CO',
      tags: ['security', 'auth'], comments: 6, attachments: 1,
      createdAt: '2025-02-22T11:00:00Z',
    },
    task_17: {
      id: 'task_17', title: 'Set up Sentry error monitoring with source maps',
      description: 'Configured Sentry DSN, uploaded source maps via CI, set up alert rules for P0 errors. Verified stack traces resolve correctly.',
      priority: 'high', dueDate: '2025-02-10', assignee: 'AK',
      tags: ['monitoring'], comments: 2, attachments: 0,
      createdAt: '2025-01-20T09:00:00Z',
    },
    task_18: {
      id: 'task_18', title: 'Implement CSV export for all data tables',
      description: 'Added streaming CSV export with proper UTF-8 BOM, column headers, and date formatting. Handles up to 100k rows without timeout.',
      priority: 'medium', dueDate: '2025-02-15', assignee: 'ZB',
      tags: ['feature'], comments: 1, attachments: 0,
      createdAt: '2025-01-22T10:00:00Z',
    },
    task_19: {
      id: 'task_19', title: 'User research: 8 interviews on onboarding friction',
      description: 'Conducted sessions with 8 target users. Synthesised findings into affinity map. Top pain point: step 3 form is too long.',
      priority: 'medium', dueDate: '2025-02-20', assignee: 'MJ',
      tags: ['research', 'ux'], comments: 3, attachments: 5,
      createdAt: '2025-01-25T11:00:00Z',
    },
    task_20: {
      id: 'task_20', title: 'Migrate CI from CircleCI to GitHub Actions',
      description: 'Ported all 14 workflow files. Parallelised test suite across 4 runners. Build time reduced from 18 min to 6 min.',
      priority: 'low', dueDate: '2025-02-25', assignee: 'ST',
      tags: ['dx', 'ci'], comments: 0, attachments: 0,
      createdAt: '2025-01-28T08:00:00Z',
    },
  },
};
